[package]
name = "xtask"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.100"
askama = "0.14.0"
axum = "0.8.6"
chrono = "0.4.42"
clap = { version = "4.5.50", features = ["derive"] }
google-cloud-storage = "1.2.0"
notify = "8.2.0"
pulldown-cmark = "0.13.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
